pipeline:
  identifier: Build_hashinyc_gosample_1746653014760
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1746652796717
        repoName: hashinyc/gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
                  timeout: ""
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    command: go test -coverprofile=coverage.out ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    command: |
                      export GOBIN=/home/harness/go/bin
                      export PATH=/home/harness/go/bin:$PATH
                      echo $PATH
                      go install github.com/jstemmer/go-junit-report/v2@latest
                      go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml
                    reports:
                      spec:
                        paths:
                          - /harness/report.xml
                      type: JUnit
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
